dependencies:
  flutter:
    sdk: flutter
  pdfx: ^latest_version  # PDF viewing support
  sqflite: ^latest_version  # Database storage for documents and metadata
  provider: ^latest_version  # State management
  path_provider: ^latest_version  # File access
  pdfx: ^latest_version
  firebase_core: ^latest_version
  cloud_firestore: ^latest_version
  firebase_auth: ^latest_version
